[build]
base    = "apps/microsite"
publish = "dist"
command = "pnpm --filter microsite... run build"

[functions]
directory = "netlify/functions"

# Pass GH secrets to the runtime automatically
[context.production.environment]
SP1RL_STAGE = "prod"
