[build]
node_version = "18"
command = "pnpm run build"
publish = "dist"

[functions]
included_files = ["*.wasm"]

[context.production.environment]
SP1RL_ENV            = "production"
PETAL_THRESHOLD      = "137"
PW_UNIT_COST         = "1"
