[build]
  command = "pnpm run build"
  publish = "dist"

[[edge_functions]]
  path = "/api/letter"
  function = "letter"

[[redirects]]
  from = "/api/letter"
  to   = "${VERCEL_URL}/api/letter"
  status = 200
