name: Deploy to Netlify

on:
  pull_request:
    paths-ignore: ["**/*.md"]
  push:
    branches: [core]

permissions:
  contents: read

jobs:
  preview:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        site: [sp1rl-os, sp1rlos]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with: {version: 9, run_install: false}
      - name: Install deps
        run: pnpm i --frozen-lockfile
        working-directory: apps/microsite
      - name: Build (CI)
        run: pnpm run build
        working-directory: apps/microsite

  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID:    ${{ secrets.NETLIFY_SITE_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with: {version: 9, run_install: false}
      - name: Install deps
        run: pnpm i --frozen-lockfile
        working-directory: apps/microsite
      - name: Build (CI)
        run: pnpm run build
        working-directory: apps/microsite
      - name: Netlify Deploy
        run: npx netlify deploy --dir dist --prod
        working-directory: apps/microsite
        env:
          NETLIFY_AUTH_TOKEN: ${{ env.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID:    ${{ env.NETLIFY_SITE_ID }}
