name: Deploy Deck
on:
  push:
    branches: [core]
    paths:
      - 'apps/deck/**'

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-pages-artifact@v2
        with:
          path: apps/deck
      - uses: actions/deploy-pages@v2
